# Header
menu:
  - name: 'Time Attack Records'
    url: '/time-attack-records'
  - name: 'Teamz'
    url: '/teamz'
    children:
      - name: 'Generator'
        url: '/teamz/generator'
      - name: 'Results'
        url: '/teamz/results'
  - name: 'Concepts'
    url: '/concepts'
    children:
      - name: 'Sandbox TA'
        url: '/concepts/sandbox-ta'
      - name: 'Set attack damage'
        url: '/concepts/set-attack-damage'
      - name: 'Frame 1 Data'
        url: '/concepts/f1-data'
  - name: 'Servers'
    url: '/servers'
    children:
      - name: 'Gamecube'
        url: '/servers/gamecube'
      - name: 'Unseen'
        url: '/servers/unseen'
  - name: 'Players'
    url: '/players'
  - name: 'Miscellaneous'
    url: '/miscellaneous'
  - name: 'PSO: TA Discord'
    url: 'https://discord.gg/q8bwhFX'

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics:
favicon: images/favicon.png
twitter:
fb_admins:
fb_app_id:
