# Header
menu:
  - name: 'Time Attack Records'
    url: '/time-attack-records'
  - name: 'Teamz'
    url: '/teamz'
    children:
      - name: 'Generator'
        url: '/teamz/generator'
      - name: 'Results'
        url: '/teamz/results'
      - name: 'Leaderboards'
        url: '/teamz/leaderboards'   
  - name: 'Concepts'
    url: '/concepts'
    children:
      - name: 'Combo Calculator'
        url: '/concepts/combo-calculator'
      - name: 'Frame 1 Data'
        url: '/concepts/f1-data'
      - name: 'Quest Warp Values'
        url: '/concepts/quest-warp-values'
      - name: 'Set Attack Damage'
        url: '/concepts/set-attack-damage'
      - name: 'Sandbox TA'
        url: '/concepts/sandbox-ta'
      - name: 'Random Writing'
        url: '/concepts/random-writing'
  - name: 'Servers'
    url: '/servers'
    children:
      - name: 'Gamecube'
        url: '/servers/gamecube'
      - name: 'Unseen'
        url: '/servers/unseen'
  - name: 'Players'
    url: '/players'
  - name: 'Miscellaneous'
    url: '/miscellaneous'
  - name: 'PSO: TA Discord'
    url: 'https://discord.gg/q8bwhFX'

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics: UA-159966586-1
twitter:
fb_admins:
fb_app_id:
